### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by Tomcli** [IBM/HyperledgerFabric-on-LinuxOne#2]
- In part 1 step 21, the command `wget https://raw.githubusercontent.com/IBM/HyperledgerFabric-on-LinuxOne/master/Linux1BlockchainScript.shW` has an extra W at the end.
- In part 2 step 47, there's a typo for the image link `ErrorMsg.png`.
- Also I guess part 3 is not ready? Since part 3 wasn't working for me.

**Comment by animeshsingh** [comment]
cc @SweetJenn23

**Comment by Tomcli** [comment]
Part 3 works for me now, although I don't think it's a good idea to put more than 1500 lines of JSON code on the README page. It just makes the user frustrated to get to the next step.

**Comment by SweetJenn23** [comment]
@Tomcli Would it be better if I just had them copy it from GitHub? I also have it stored on GitHub in the code folder.
