### ISSUE TITLE
Too many steps in the main README

### ISSUE THREAD

**Issue by Tomcli** [IBM/HyperledgerFabric-on-LinuxOne#3]
It's very nice to have each step in details. However, having too many steps on the GitHub README makes it harder for users to keep up. Some of the steps are repetitive and could be combined into one step. E.g. In part 2, there are too many repetitive steps for how to import each file.

**Comment by animeshsingh** [comment]
cc @SweetJenn23

**Comment by SweetJenn23** [comment]
@Tomcli Can you quickly review this part of Part 2 again?

**Comment by Tomcli** [comment]
It looks better to me, although the step numbering is off (e.g. you jumped from step 24 to 35). Since the journey still have many steps, so the numbering has to be correct in order to avoid confusion. Also there's a broken image link in part 3.
